@startuml Publish Context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
LAYOUT_WITH_LEGEND()
System(asset_management, "Asset Management", "Manages inventory")
System(pricing, "Pricing", "Calculate and update vehicle pricing")
System(vehicle_data, "Vehicle Data", "Aggregates vehicles data from external providers")
System(refurb, "Refurb", "Verify features")
System(publish, "Publish", "Vehicle listing and publish to channels")
System_Ext(autos_on_show, "Autos On Show", "provide vehicle imagery")
System_Ext(autotrader, "Autotrader", "vehicle classified aggregator")
System_Ext(motors_co_uk, "Motors.co.uk", "vehicle classified aggregator")
System_Ext(commerce_tools, "Commerce Tools", "ecommerce platform")
Rel(asset_management, publish, "Notifies about New Vehicles to")
Rel(autos_on_show, publish, "Notifies about photographed Vehicles to")
Rel(publish,autos_on_show, "Reads images from")
Rel(pricing, publish, "Sends vehicle price update to")
Rel(publish, pricing, "Triggers vehicle price loop on")
Rel(publish, vehicle_data, "Retrieves vehicle data from")
Rel(refurb, publish, "Sends vehicle feature list to")
Rel(publish, commerce_tools, "Publishes listing to")
Rel(commerce_tools, publish, "Send sales orders to")
Rel(publish, motors_co_uk, "Publishes listing to")
Rel(publish, autotrader, "Publishes listing to")
@enduml